### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by ArneBachmannDLR** [xnuinside/codegraph#10]
Getting this on Python 3.11:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\bach_ar\.conda\envs\311\Scripts\cg.exe\__main__.py", line 7, in <module>
  File "C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\codegraph\main.py", line 18, in cli
    main(args)
  File "C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\codegraph\main.py", line 22, in main
    usage_graph = core.CodeGraph(args).usage_graph()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\codegraph\core.py", line 75, in usage_graph
    entities_lines, imports, modules_names_map = get_imports_and_entities_lines(self.modules_data)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bach_ar\.conda\envs\311\Lib\site-packages\codegraph\core.py", line 126, in get_imports_and_entities_lines
    pathed_import, alias = pathed_import.split(' as ')
    ^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

Maybe the "import ... as ... " is not correctly supported?
The last file shown before the error was `__main__.py` which is always kind of special, the code in question might be this somewhat messed up line:
`if '--imports' in sys.argv: from .progress import setup as import_logger; import_logger()`

**Comment by xnuinside** [comment]
@ArneBachmannDLR, hello! Thanks for opening the issue, I will take a look on it later

**Comment by Kedarnath-Rothe** [comment]
![image](https://github.com/xnuinside/codegraph/assets/143418802/b9091094-c08d-48da-8e9d-062450f8aca7)

**Comment by Kedarnath-Rothe** [comment]
Please assign to me

**Comment by xnuinside** [comment]
I hope this issue should be resolved in version 1.0.0
