### ISSUE TITLE
Error installing on OSX (M2 pro)

### ISSUE THREAD

**Issue by ruze00** [xnuinside/codegraph#12]
When I try to install with `pip install codegraph` on a Macbook M2 Pro I get this error:

```
Collecting codegraph
  Using cached codegraph-0.0.7-py3-none-any.whl.metadata (2.5 kB)
Collecting clifier<0.0.4,>=0.0.3 (from codegraph)
  Using cached clifier-0.0.3-py3-none-any.whl.metadata (487 bytes)
Collecting matplotlib<4.0,>=3.1 (from codegraph)
  Using cached matplotlib-3.8.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.8 kB)
Collecting networkx<3.0,>=2.4 (from codegraph)
  Using cached networkx-2.8.8-py3-none-any.whl.metadata (5.1 kB)
Collecting PyYAML<6.0,>=5.3 (from clifier<0.0.4,>=0.0.3->codegraph)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/ruze/anaconda3/envs/rcp/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/ruze/anaconda3/envs/rcp/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ruze/anaconda3/envs/rcp/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/4c/gj_7pgbx32v_ppgrrl8m7cv40000gn/T/pip-build-env-wt3mmix3/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ruze00** [comment]
Solution: I removed the clifier dependency.
